/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.devkb;

public class Application {
    public String getGreeting() {
        return "Hello BONGBONG";
    }

    public static void main(String[] args) {
        System.out.println(new Application().getGreeting());
    }
}

